name: 🐛 Bug Report
description: Etwas funktioniert nicht wie erwartet
title: "[Bug]: "
labels: ["🐛 bug"]
body:
  - type: input
    id: typo3-version
    attributes:
      label: TYPO3-Version
      placeholder: z.B. 13.4.2
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: t3sbootstrap-Version
      placeholder: z.B. 5.2.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Was ist passiert?
      description: Beschreibe das Problem und wie man es reproduziert.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true
