name: 🐛 Bug Report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["🐛 bug"]
body:
  - type: input
    id: typo3-version
    attributes:
      label: TYPO3-Version
      placeholder: z.B. 14.3
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: t3sbootstrap-Version
      placeholder: z.B. 5.3.42
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the problem and how to reproduce it.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
