name: ✨ Feature Request
description: Vorschlag für eine neue Funktion
title: "[Feature]: "
labels: ["✨ feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem löst das Feature?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Lösungsvorschlag
    validations:
      required: true
